### ISSUE TITLE
update auto create date 

### ISSUE THREAD

**Issue by ghost** [teqnodude/glftpd-installer#10]
can you make a update so EBOOKS also have audo create date like MP3 FLAC and 0DAY

section=${section^^}
	if [[ ${section^^} = 0DAY || ${section^^} = FLAC || ${section^^} = MP3 ]] 
	then

**Comment by teqnodude** [comment]
Fixed. 

I have now included EBOOKS as one of the sections available during install. You can read more about the changes [here](https://github.com/teqnodude/glftpd-installer/commit/6fcbab0999681d62e940889be231ba6548c018b2).
