### ISSUE TITLE
Error in ./section_manager.sh

### ISSUE THREAD

**Issue by ghost** [teqnodude/glftpd-installer#11]
hey

there are a error when you try ./section_manager.sh

can you take a look at that :-)

./section_manager.sh: line 361: syntax error in conditional expression: unexpected token `;'
./section_manager.sh: line 361: syntax error near `;'
./section_manager.sh: line 361: `if [[ "$(ls $glroot/site | grep -iw ^0DAY | tr '[a-z]' '[A-Z]')" != "0DAY" && "$(ls $glroot/site | grep -w ^FLAC | tr '[a-z]' '[A-Z]')" != "FLAC" && "$(ls $glroot/site | grep -w ^MP3 | tr '[a-z]' '[A-Z]')" != "MP3" && "$(ls $glroot/site | grep -w ^EBOOKS | tr '[a-z]' '[A-Z]')" != "EBOOKS"]] ;'

**Comment by teqnodude** [comment]
[Fixed](https://github.com/teqnodude/glftpd-installer/commit/9ab9eeeaf60f44046ca1b4a8d7d05436f13eab9f)
