### ISSUE TITLE
Mabye add this script here

### ISSUE THREAD

**Issue by ghost** [teqnodude/glftpd-installer#12]
first dunno how to pull request so i put it in here 

mabye you have time to pull https://github.com/signor-/glftpd/blob/master/sig-archive_move/sig-archive_move.sh into you awesome script for i doing it manual atm :-(

**Comment by teqnodude** [comment]
[tur-archiver](https://algorhythm.cc/content/Tur/archiver/tur-archiver_2.5.tar.gz) is a far better script in my view since it offers different modalities of archiving too like copy, move and symlink.

**Comment by ghost** [comment]
i looks good we take that one :-P do you have time to custom it to you auto installer ?

**Comment by teqnodude** [comment]
I have [added](https://github.com/teqnodude/glftpd-installer/commit/2f6a60834dbdc2a8e26fcc80dbce3f260fa3a568) it as part of the installation but for now the settings will have to be manually configured after install.
