### ISSUE TITLE
issues with archive and rel question 

### ISSUE THREAD

**Issue by Ghost-L33t** [teqnodude/glftpd-installer#13]
hey 

i have a issues with ARCHIVE when i upload files to that folder it dosent complete the full release only NFO and and SFV file do i have to change something it one of the script so i dosent have to check ever time there are a new rel i will put in archive ?

another question i have tryed all day to see if i can find something in the scripts about how do who have uploaded the file to irc 

fx NEW RELEASE ] [ BLURAY ] [ The.Other.Lamb.2019.DUAL.COMPLETE.BLURAY-GLiMMER by Supreme how do i remove the user and only keep NEW RELEASE ] [ BLURAY ] [ The.Other.Lamb.2019.DUAL.COMPLETE.BLURAY-GLiMMER

hope you have a tip for that :-)

**Comment by teqnodude** [comment]
Once again you are asking questions that has no relevance to the installation script. I'm closing the issue and I would encourage you from not creating issues that are not related to this installer. This is not a "ask any question you want" kind of place.
