### ISSUE TITLE
Sitebot error

### ISSUE THREAD

**Issue by Zignet64** [teqnodude/glftpd-installer#3]
Hello,

I test last version and get this error during script.
All works except sitebot :) 

```
./install.sh: line 149: groupadd: command not found
./install.sh: line 155: useradd: command not found
chfn: user 'sitebot' does not exist
```
Thanks for this very helpful script.
PS: is there a way to add or customize section ?

**Comment by teqnodude** [comment]
In what distribution have you run the script in and did you run as root?

"PS: is there a way to add or customize section ?"
You can add / remove sections with section_manager.sh located in /glftpd

**Comment by Zignet64** [comment]
Debian 10
Linux version 4.19.0-6-amd64 (debian-kernel@lists.debian.org) (gcc version 8.3.0 (Debian 8.3.0-6)) #1 SMP Debian 4.19.67-2+deb10u2 (2019-11-11)

And yes run as root.

Nice addon section_manager.sh :)

**Comment by teqnodude** [comment]
For some reason the `passwd` package is not installed for you, it should be. Run the `cleanup.sh` script in the glftpd installer to uninstall glftpd and it's scripts and then run `apt-get install passwd` to install the package containing useradd and run the glftpd installer once again.

**Comment by teqnodude** [comment]
I have updated README.MD to include `passwd` package in the list of requirements to prevent this problem from happening again. Closing this issue.

**Comment by Zignet64** [comment]
Re,
Sorry not better, and package already install on debian

_apt-get install passwd
Reading package lists... Done
Building dependency tree       
Reading state information... Done
passwd is already the newest version (1:4.5-1.1)._

Clean
and restart with install.cache
Same error (see attached)
[glftpd_script.txt](https://github.com/teqnodude/glftpd-installer/files/4007356/glftpd_script.txt)

For information, use always with method Unattended installation (install.cache)

Thanks.

**Comment by teqnodude** [comment]
Ok so the package is installed but the installer script can't find the files. Only thing I can think of is this.

Environmental path is not set up correctly in your system which makes it impossible for the script to find the files `groupadd` `useradd `and `chfn`. Do the command `env | grep PATH`, it should list `/usr/bin` and `/usr/sbin`. If it doesn't you need to update PATH by doing the command `export PATH=$PATH:/usr/bin:/usr/sbin`
After you done that do the commands `whereis groupadd` `whereis useradd` and `whereis chfn` and see if it can find the files. If it can find the files then try run the commands manually without arguments ie `groupadd` `useradd` and `chfn`. If that works then the installer should work.

**Comment by Zignet64** [comment]
The debian server is by default nothing change/custom.

With actual path env config : 
Files seem exist (but not the good)


```
root@zStorage:/# env | grep PATH
PATH=/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games

```
```
root@zStorage:/# env | grep PATH
PATH=/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games

root@zStorage:/# whereis groupadd
groupadd: /usr/sbin/groupadd /usr/share/man/man8/groupadd.8.gz

root@zStorage:/# whereis useradd
useradd: /usr/sbin/useradd /usr/share/man/man8/useradd.8.gz

root@zStorage:/# whereis chfn
chfn: /usr/bin/chfn /usr/share/man/man1/chfn.1.gz

```
```

root@zStorage:/# groupadd
bash: groupadd: command not found

root@zStorage:/# useradd
bash: useradd: command not found

root@zStorage:/# chfn
Changing the user information for root
Enter the new value, or press ENTER for the default
        Full Name [root]: ^C
```

After export : 
PATH=/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games:/usr/bin:/usr/sbin

```
```
root@zStorage:/# groupadd 
Usage: groupadd [options] GROUP

Options:
  -f, --force                   exit successfully if the group already exists,
                                and cancel -g if the GID is already used
  -g, --gid GID                 use GID for the new group
  -h, --help                    display this help message and exit
  -K, --key KEY=VALUE           override /etc/login.defs defaults
  -o, --non-unique              allow to create groups with duplicate
                                (non-unique) GID
  -p, --password PASSWORD       use this encrypted password for the new group
  -r, --system                  create a system account
  -R, --root CHROOT_DIR         directory to chroot into

root@zStorage:/# useradd



```
root@zStorage:/# useradd
Usage: useradd [options] LOGIN
       useradd -D
       useradd -D [options]

Options:
  -b, --base-dir BASE_DIR       base directory for the home directory of the
                                new account
  -c, --comment COMMENT         GECOS field of the new account

```


After reboot

root@zStorage:~# env | grep PATH
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

Clean
install 

No more errors !

For the path i don't know why /usr/sbin was missing ... 
install from ISO Debian 10 / install minimal.

Thanks :)

**Comment by teqnodude** [comment]
No problem, glad it worked. Closing the issue.
