### ISSUE TITLE
Pre Bot and other questions :-)

### ISSUE THREAD

**Issue by ghost** [teqnodude/glftpd-installer#9]
Hey Teq

i have some question about you awesome glftpd-installer script 

some reason i cant do nothing in pull request so i made a issues post insted

1: will you make a pre bot for you great script ?
2: will  you make a guide how to install script in mysql or mariadb ?
3:what about make a installation script for unrealircd server so ppl can get there own server when you already have eggdrop bot in you script ?

peace out and keep up the great work mate

**Comment by teqnodude** [comment]
1. No and even if I wanted to I don't think I could make one since it's not as simple as people think.
2. What script are you referring to? 
3. No, not at this point anyway.

**Comment by ghost** [comment]
> 1. No and even if I wanted to I don't think I could make one since it's not as simple as people think.
> 2. What script are you referring to?
> 3. No, not at this point anyway.

1: i know it's not that simple to make a script for pre bot thats why many use relay bot but it's not allowed to use (but if you have some scripts i can help looking at them ) dunno how to send private message to other on github
2: i have a huge Pre Database i want to get into the mariadb i installed with you script but dont know how to set it up for that
3: ok hope you change you mind for that will help alot of ppl for you script are awesome and need that :-)

**Comment by teqnodude** [comment]
1. Not interested at this point.
2. Not relevant to the installer.

Closing this issue.
